services:
  frontend:
    container_name: frontend
    build:
      context: ./admin
      dockerfile: Dockerfile
    ports:
      - 9000:9000
    volumes:
      - admin_data:/app
    environment:
      - NODE_ENV=development
    depends_on:
      - backend
    networks:
      - frontend_network
  backend:
    container_name: backend
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - api_data:/app
    networks:
      - frontend_network
volumes:
  admin_data:
  api_data:
networks:
  frontend_network:
    driver: bridge
