stages:
  - deploy

deploy pre:
  stage: deploy
  script:
    - npm install
    - pm2 start pm2/preproduction.yml
  environment:
    name: preproduction
    url: https://pre.api.eurekacloud.es
  when: manual
  tags:
    - pre
    - aws
    - back

deploy pro:
  stage: deploy
  script:
    - npm install
    - pm2 start pm2/production.yml
  only:
    - master
  when: manual
  environment:
    name: production
    url: https://api.eurekacloud.es
  tags:
    - eureka
    - pro
